name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }} 
          script: |
            APP_DIR="/home/${USER:-ec2-user}/fastapi-book-project"

            if [ -d "$APP_DIR" ]; then
              echo "Directory exists. Pulling latest code..."
              cd "$APP_DIR"
              git pull
            else
              echo "Directory does not exist. Cloning repository now..."
              git clone https://github.com/oyogbeche/fastapi-book-project.git "$APP_DIR"
              cd "$APP_DIR"
            fi

            docker stop books-api || true
            docker rm books-api || true

            docker build -t books-api:latest .

            docker run -d --name books-api -p 8000:8000 books-api:latest